version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - '4000:4000'

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - '5173:5173'
